### ISSUE TITLE
Detalhe da associação entre Pedido e ItemPedido

### ISSUE THREAD

**Issue by cslclaman** [cslclaman/pooPrj1#15]
O diagrama de classes/enunciado do trabalho diz que:

> A cada ligação com um objeto ItemPedido o valor do item deve ser subtraído do limite
disponível do Cliente.

Valeria a pena criar um método como "diminuirLimite()" na classe de Cliente? Ou melhor usar o setLimiteDisponivel() para isso?

**Comment by Allanflo88** [comment]
Melhor utilziar setLimiteDisponivel()
