### ISSUE TITLE
Classe Pedido: Atributo Número

### ISSUE THREAD

**Issue by cslclaman** [cslclaman/pooPrj1#16]
As boas práticas de Java dizem que atributos devem iniciar em letras minúsculas, mas o diagrama de classes colocou o atributo Número com inicial maiúscula. Ao modelar, foi seguido o que está definido no diagrama (ou seja, Numero ficou com inicial maiúscula), mas seria melhor abrir uma exceção ao diagrama e manter a boa prática?

**Comment by Allanflo88** [comment]
Prefiro seguir a boa prática, mas deixemos para resolver isso Segunda com o Dimas.

**Comment by cslclaman** [comment]
Eu abri esse issue para lembrarmos de perguntar para o Dimas... E eu preferia que continuasse aberto.
