### ISSUE TITLE
Aplic1-É necessário verificar alguns atributos?

### ISSUE THREAD

**Issue by Iarton** [cslclaman/pooPrj1#17]
Exemplos:
Verificar se há ainda produtos.
Verificar se os produtos estão acima do estoque minimo.
Verificar se Cliente ainda tem limite.

**Comment by cslclaman** [comment]
Como isso não tinha sido pedido no enunciado, acredito que não precisa fazer tantas validações.
A ideia é só verificar se, a cada item adicionado no pedido, o estoque daquele produto está sendo devidamente descontado e se o limite do cliente está sendo diminuído. Se ficar negativo, por enquanto não vamos nos preocupar.

**Comment by Iarton** [comment]
Okei, se eu tiver tempo, talvez eu faça as verificações, o resto do projeto esta correto.
(Acho que vou fazer as verificações)
