### ISSUE TITLE
Verificar associação entre Cliente-Pedido e Vendedor-Pedido

### ISSUE THREAD

**Issue by cslclaman** [cslclaman/pooPrj1#18]
Divergências de implementação:
Eu, @Allanflo88 : a associação deve ser feita no pedido (ou seja, quando você cria o pedido, associa um cliente e um vendedor (ou, no caso de uma loja real, poderia até criar o cliente na hora do pedido). Do ponto de vista de regras de negócio, isso faz mais sentido.
@Iarton: a associação deve ser feita no cliente (ao adicionar o pedido na lista de pedidos do cliente) e no vendedor (ao adicionar o pedido na lista de pedidos do vendedor). Isso está de acordo com os projetos que usamos como exemplo.
Essa é uma dúvida interessante, pois a associação funciona corretamente em qualquer um dos jeitos de implementação. Porém, do ponto de vista da modelagem, teríamos que ver qual é a maneira "adequada" de fazer essas associações.

**Comment by Iarton** [comment]
Mas no documento de Exercício pede para ser Cliente-Pedido e Vendedor-Pedido
Ele pede para o ArrayList ser no Cliente e Vendedor assim como ele pede para associar o ItemPedido no Pedido(Claro que neste caso não há duvidas)

**Comment by cslclaman** [comment]
Verdade, agora está certo conforme o enunciado. Não tinha lembrado de ver aquela parte da explicação.
